### PR TITLE
Added functionnality: Ability to close linked issue from pull requests

### PR DESCRIPTION
**Pull request by soflass1293**
**Close linked issue**
While viewing a pull request of a branch having an issue linked to it you can close the linke issue right from the pull request

image

**Linked issue already closed**
If the linked issue is already closed the button will display that the linked issue is already closed and it will be disabled

image

**Additional links**
You can find links to the linked issue as well as the source branch

### CODE REVIEW

**Comment by bumbeishvili** [comment]
This is interesting, merging

**Comment by bumbeishvili** [comment]
@soflass1293 I think it had some bugs, so I am gonna revert it

**Comment by bumbeishvili** [comment]
@soflass1293  for future PR's, can you include a gif or video describing how the feature works?

**Comment by soflass1293** [comment]
Okay, I will include a video or a GIF

**Comment by soflass1293** [comment]
Sorry for the late response, I was tying to upload the video but with no luck (because of the GitHub file limit).
I shared the video into Google Drive, here is the link

https://drive.google.com/file/d/1Wk38fZRvddZ_cuQkpL63A0D82ZoGmzJ1/view?usp=sharing

**Pull request merged**
